/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.LoginController;
import Controller.PrincipalController;
import javax.swing.JOptionPane;

/**
 *
 * @author Segismar Junior
 */
public class TelaCadastroMetas extends javax.swing.JPanel {
    private PrincipalController principal;
    /**
     * Creates new form TelaCadastroMetas
     */
    public TelaCadastroMetas() {
        initComponents();
        this.principal = new PrincipalController();
        txtValor.setDocument(new TeclasPermitidasDouble());
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Background = new javax.swing.JPanel();
        pnTitulo = new javax.swing.JPanel();
        lblTituloPage = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIconPage = new javax.swing.JLabel();
        separaMeta = new javax.swing.JSeparator();
        pn_DadosMetas = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        smLimite = new javax.swing.JSlider();
        lblCategoria = new javax.swing.JLabel();
        lblPor_mes = new javax.swing.JLabel();
        lblMeses = new javax.swing.JLabel();
        lblNumMes = new javax.swing.JLabel();
        lblPretendoGastar = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox();
        btnCadastrar = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();

        pn_Background.setBackground(new java.awt.Color(255, 255, 255));
        pn_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTitulo.setBackground(new java.awt.Color(49, 76, 212));

        lblTituloPage.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblTituloPage.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPage.setText("Cadastro de Metas");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Metas");

        lblIconPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/home-icon.png"))); // NOI18N

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo)
                    .addGroup(pnTituloLayout.createSequentialGroup()
                        .addComponent(lblIconPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloPage)))
                .addContainerGap(456, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIconPage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloPage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addContainerGap())
        );

        separaMeta.setForeground(new java.awt.Color(255, 255, 255));

        pn_DadosMetas.setBackground(new java.awt.Color(255, 255, 255));
        pn_DadosMetas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValor.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblValor.setText("R$");
        pn_DadosMetas.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 40));

        smLimite.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        smLimite.setMaximum(12);
        smLimite.setMinimum(1);
        smLimite.setToolTipText("");
        smLimite.setValue(1);
        smLimite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                smLimiteStateChanged(evt);
            }
        });
        pn_DadosMetas.add(smLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 180, 30));

        lblCategoria.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        lblCategoria.setText("Com:");
        pn_DadosMetas.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        lblPor_mes.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        lblPor_mes.setText("Por:");
        pn_DadosMetas.add(lblPor_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblMeses.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        lblMeses.setText("meses");
        pn_DadosMetas.add(lblMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 50, -1));

        lblNumMes.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        lblNumMes.setText("1");
        pn_DadosMetas.add(lblNumMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 20, -1));

        lblPretendoGastar.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        lblPretendoGastar.setText("Pretendo gastar:");
        pn_DadosMetas.add(lblPretendoGastar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cmbCategoria.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comida", "Lazer", "Roupa", "Saúde", "Veículo", "Esporte", "Familiar" }));
        cmbCategoria.setToolTipText("");
        cmbCategoria.setBorder(null);
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        pn_DadosMetas.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 170, 30));

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        pn_DadosMetas.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 110, 30));

        txtValor.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N
        txtValor.setForeground(new java.awt.Color(255, 0, 0));
        pn_DadosMetas.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(separaMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pn_DadosMetas, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(pn_Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separaMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_DadosMetas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(pn_Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void smLimiteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_smLimiteStateChanged
        lblNumMes.setText(String.valueOf(smLimite.getValue()));
    }//GEN-LAST:event_smLimiteStateChanged

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        double valor;    
        valor = Double.parseDouble(txtValor.getText().replace(',', '.'));
        
        String categoria = cmbCategoria.getSelectedItem().toString();
        int limite = smLimite.getValue();
               
        if(this.principal.encaminhaMeta(categoria, valor, limite)){
            JOptionPane.showMessageDialog(null, "Meta Cadastrada");
        }
        
    }//GEN-LAST:event_btnCadastrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblIconPage;
    private javax.swing.JLabel lblMeses;
    private javax.swing.JLabel lblNumMes;
    private javax.swing.JLabel lblPor_mes;
    private javax.swing.JLabel lblPretendoGastar;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTituloPage;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JPanel pn_Background;
    private javax.swing.JPanel pn_DadosMetas;
    private javax.swing.JSeparator separaMeta;
    private javax.swing.JSlider smLimite;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
